### ISSUE TITLE
It seems I can't to deploy it on Heroku

### ISSUE THREAD

**Issue by Sanaselasa** [salcido/reddibot#1]
Hello I tried to deploy it to Heroku but it seems I'm getting an error. I'm alreddy running it on Node.js and working perfectly fine tho.

> 
> twicereddibot@1.0.0 start /app
> node bot.js

> 
> /app/node_modules/twit/lib/twitter.js:511
>       throw new Error(err_msg)
>       ^
> 
> Error: Twit config must include `consumer_key` when using user auth.
>     at /app/node_modules/twit/lib/twitter.js:511:13
>     at Array.forEach (<anonymous>)
>     at Twitter._validateConfigOrThrow (/app/node_modules/twit/lib/twitter.js:508:17)
>     at new Twitter (/app/node_modules/twit/lib/twitter.js:58:8)
>     at Object.<anonymous> (/app/bot.js:53:17)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! twicereddibot@1.0.0 start: `node bot.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the twicereddibot@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /app/.npm/_logs/2019-02-05T08_42_29_066Z-debug.log
> 

So any solution for this error?

**Comment by salcido** [comment]
It looks like you are missing the `consumer_key` in the `.env` file. Did you upload that to Heroku?
