### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: timeline.some is not a function

### ISSUE THREAD

**Issue by AddaxSoft** [salcido/reddibot#19]
The bot doesn't post anything on twitter, and i'm faced with this error here:

```
(node:2728) UnhandledPromiseRejectionWarning: TypeError: timeline.some is not a function
    at getNextPost (/home/limited/reddibot/bot.js:131:20)
    at getPostsAndTimeline.then (/home/limited/reddibot/bot.js:316:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:2728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 141)

```

running in a Ubuntu
Python 2.7.12

**Comment by salcido** [comment]
My guess is that you are using an older version of Node. Try updating Node or (if that doesn't work) you can [add a polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some#Polyfill) for `Array.prototype.some` to [bot.js](https://github.com/salcido/reddibot/blob/master/bot.js).
